name: Build ,Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install npm dependencies
      run: npm install
    - name: Display softuni username
      run: echo 'aisunaihan'
    - name: Execute unit tests
      run: npm run test:unit

  execute-ui-test:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Start the application
      run: npm run start &
    - name: Execute ui tests
      run: npm run test:ui
  
  deploy:
    needs: execute-ui-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_KEY}}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true


